[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

; Hạ xung nhịp CPU xuống mức trung bình để tiết kiệm điện
board_build.f_cpu = 160000000L
; Hạ xung nhịp Flash xuống mức an toàn
board_build.f_flash = 40000000L
; Chế độ Flash DIO ổn định hơn QIO khi nguồn yếu
board_build.flash_mode = dio

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue